SELECT
    m.WEBHOOK_URL,
    COUNT(DISTINCT p.ID) AS total_payments,
    COUNT(DISTINCT CASE WHEN p.STATUS = 'CAPTURED' THEN p.ID END) AS SUCCESSFUL_PAYMENTS,
    COUNT(DISTINCT CASE WHEN p.STATUS = 'AUTHORISED' THEN p.ID END) AS PENDING_PAYMENTS,
    COUNT(DISTINCT CASE WHEN p.STATUS = 'UNAUTHORISED' THEN p.ID END) AS FAILED_PAYMENTS,
    SUM(p.AMOUNT) AS REVENUE,
    COUNT(DISTINCT u.id) AS UNIQUE_USERS_COUNT,
    COUNT(DISTINCT CASE WHEN p.STATUS = 'UNAUTHORISED' THEN p.ID END)
        / COUNT(DISTINCT p.ID) AS FRAUD_RATE
FROM {{ ref('fact_payments') }} p
LEFT JOIN {{  ref('dim_users') }} u
    ON p.masked_card_pan = u.masked_card_pan
LEFT JOIN {{ ref('dim_merchants') }} m
    ON p.merchant_id = m.id
GROUP BY m.WEBHOOK_URL
ORDER BY m.WEBHOOK_URL