"""users

Revision ID: 0edac6bb7927
Revises: 448aad46311d
Create Date: 2026-05-23 13:58:02.139613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0edac6bb7927'
down_revision: Union[str, Sequence[str], None] = '448aad46311d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'user_id')
    # ### end Alembic commands ###
