"""rename column to fraud_score in transaction

Revision ID: a1b670e29866
Revises: d39c5c20535f
Create Date: 2026-05-17 15:38:05.324275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b670e29866'
down_revision: Union[str, Sequence[str], None] = 'd39c5c20535f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('fraud_score', sa.Float(), nullable=True))
    op.drop_column('transactions', 'risk_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'fraud_score')
    # ### end Alembic commands ###
