"""Check schema

Revision ID: d39c5c20535f
Revises: 539ea5979554
Create Date: 2026-05-17 12:17:48.578023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39c5c20535f'
down_revision: Union[str, Sequence[str], None] = '539ea5979554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('risk_score', sa.Float(), nullable=True))
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transactions', 'risk_score')
    # ### end Alembic commands ###
